version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A service_time worker -l info
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/app

#  nginx:
#    image: nginx:latest
#    ports:
#      - "443:443"  # Для HTTPS
#      - "80:80"    # Для HTTP
#    volumes:
#      - ./certs:/etc/nginx/certs
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    restart: always
#    depends_on:
#      - web  # Nginx должен зависеть от web-сервиса

volumes:
  data:
  redisdata:
#  certs:  # Папка для сертификатов
